version: "2"
services:
  prometheus:
    image: prom/prometheus:v2.33.1
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.2.2-ubuntu
    ports:
      - 3000:3000
    container_name: grafana
    restart: always
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      -  ./grafana-lib:/var/lib/grafana
      - ./grafana-etc:/etc/grafana
      - ./grafana-log:/var/log/grafana

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    expose:
      - 9100

